### ISSUE TITLE
ATT Editor treats colors other than pure black as transparent

### ISSUE THREAD

**Issue by Vermidia** [bedalton/Caos-Plugin-IntelliJ#32]
Breeds that use colors like #010101 or #101010 have those colors treated as transparent, when in game they're visible.

**Comment by bedalton** [comment]
I am unable to replicate this behavior. Can you provide an example sprite?

Alternatively, can you dump the sprite and either provide a problematic image, or check the visible blacks and see if they really are #010101 or #101010, as they may have been changed during compile?

You can dump the sprite in IntelliJ by:
1. Right clicking on the sprite in the project tree
2. Select "Dump Sprite Images"
3. Select output folder
4. Click "okay"

**Comment by Vermidia** [comment]
Dumping the sprite makes the blacks transparent. When I open the c16 in Spritiist or in-game, the blacks are not transparent as expected. I can provide the sprite here, but for a different example, Golden Desert Norns from c2 have transparent squares in their ears when opened up with the plugin.

[Non-black eyes.zip](https://github.com/bedalton/Caos-Plugin-IntelliJ/files/13360175/Non-black.eyes.zip)

Provided is the c16 and original png. They were compiled using Spritist aswell.

**Comment by bedalton** [comment]
Spritist encodes and outputs the image with pure black, which is part of the problem. You can see that with any frame dumped by Spritist itself.

Transparent black though is written to the sprite file differently than color. What I did not realize is that if pure black is written like a color. It is visible as pure black.
